# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/git_repos/mnist_neuralnet/fpga/projects/9_18/9_18.srcs/sources_1/bd/PL_NN/ip/PL_NN_image_loader_module_0_1/PL_NN_image_loader_module_0_1.xci
# IP: The module: 'PL_NN_image_loader_module_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/git_repos/mnist_neuralnet/fpga/projects/9_18/9_18.srcs/sources_1/bd/PL_NN/perceptron/rtl/src/axi_bram_ctrl_0/axi_bram_ctrl_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_bram_ctrl_0 || ORIG_REF_NAME==axi_bram_ctrl_0} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/projects/9_18/9_18.srcs/sources_1/bd/PL_NN/perceptron/rtl/src/blk_mem_gen_0/blk_mem_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# XDC: c:/git_repos/mnist_neuralnet/fpga/projects/9_18/9_18.srcs/sources_1/bd/PL_NN/perceptron/rtl/src/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc

# IP: C:/git_repos/mnist_neuralnet/fpga/projects/9_18/9_18.srcs/sources_1/bd/PL_NN/ip/PL_NN_image_loader_module_0_1/PL_NN_image_loader_module_0_1.xci
# IP: The module: 'PL_NN_image_loader_module_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/git_repos/mnist_neuralnet/fpga/projects/9_18/9_18.srcs/sources_1/bd/PL_NN/perceptron/rtl/src/axi_bram_ctrl_0/axi_bram_ctrl_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_bram_ctrl_0 || ORIG_REF_NAME==axi_bram_ctrl_0} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/projects/9_18/9_18.srcs/sources_1/bd/PL_NN/perceptron/rtl/src/blk_mem_gen_0/blk_mem_gen_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# XDC: c:/git_repos/mnist_neuralnet/fpga/projects/9_18/9_18.srcs/sources_1/bd/PL_NN/perceptron/rtl/src/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc
