# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_3/design_3.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_3 || ORIG_REF_NAME==design_3} -quiet] -quiet

# IP: bd/design_3/ip/design_3_processing_system7_0_0/design_3_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_3_processing_system7_0_0 || ORIG_REF_NAME==design_3_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_axi4_lite_register_m_0_0/design_3_axi4_lite_register_m_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_3_axi4_lite_register_m_0_0 || ORIG_REF_NAME==design_3_axi4_lite_register_m_0_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_xbar_1/design_3_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_3_xbar_1 || ORIG_REF_NAME==design_3_xbar_1} -quiet] -quiet

# IP: bd/design_3/ip/design_3_axi_interconnect_0_0/design_3_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_3_axi_interconnect_0_0 || ORIG_REF_NAME==design_3_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_axi_gpio_0_0/design_3_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_3_axi_gpio_0_0 || ORIG_REF_NAME==design_3_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_proc_sys_reset_0_0/design_3_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_3_proc_sys_reset_0_0 || ORIG_REF_NAME==design_3_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_image_loader_module_0_0/design_3_image_loader_module_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_3_image_loader_module_0_0 || ORIG_REF_NAME==design_3_image_loader_module_0_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_ila_0_0/design_3_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_3_ila_0_0 || ORIG_REF_NAME==design_3_ila_0_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_perceptron_0_1/design_3_perceptron_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_3_perceptron_0_1 || ORIG_REF_NAME==design_3_perceptron_0_1} -quiet] -quiet

# IP: bd/design_3/ip/design_3_xlconstant_0_1/design_3_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_3_xlconstant_0_1 || ORIG_REF_NAME==design_3_xlconstant_0_1} -quiet] -quiet

# IP: bd/design_3/ip/design_3_axi_gpio_1_0/design_3_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_3_axi_gpio_1_0 || ORIG_REF_NAME==design_3_axi_gpio_1_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_auto_pc_0/design_3_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_3_auto_pc_0 || ORIG_REF_NAME==design_3_auto_pc_0} -quiet] -quiet

# XDC: bd/design_3/design_3_ooc.xdc
