# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/git_repos/mnist_neuralnet/fpga/source/perceptron/rtl/src/blk_mem_gen_0/blk_mem_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# Block Designs: bd/PL_NN_prototype/PL_NN_prototype.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_NN_prototype || ORIG_REF_NAME==PL_NN_prototype} -quiet] -quiet

# IP: bd/PL_NN_prototype/ip/PL_NN_prototype_axi4_lite_register_m_0_0/PL_NN_prototype_axi4_lite_register_m_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_NN_prototype_axi4_lite_register_m_0_0 || ORIG_REF_NAME==PL_NN_prototype_axi4_lite_register_m_0_0} -quiet] -quiet

# IP: bd/PL_NN_prototype/ip/PL_NN_prototype_xbar_0/PL_NN_prototype_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_NN_prototype_xbar_0 || ORIG_REF_NAME==PL_NN_prototype_xbar_0} -quiet] -quiet

# IP: bd/PL_NN_prototype/ip/PL_NN_prototype_axi_interconnect_0_0/PL_NN_prototype_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_NN_prototype_axi_interconnect_0_0 || ORIG_REF_NAME==PL_NN_prototype_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/PL_NN_prototype/ip/PL_NN_prototype_axis_broadcaster_0_0/PL_NN_prototype_axis_broadcaster_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_NN_prototype_axis_broadcaster_0_0 || ORIG_REF_NAME==PL_NN_prototype_axis_broadcaster_0_0} -quiet] -quiet

# IP: bd/PL_NN_prototype/ip/PL_NN_prototype_image_loader_module_0_0/PL_NN_prototype_image_loader_module_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_NN_prototype_image_loader_module_0_0 || ORIG_REF_NAME==PL_NN_prototype_image_loader_module_0_0} -quiet] -quiet

# IP: bd/PL_NN_prototype/ip/PL_NN_prototype_perceptron_0_0/PL_NN_prototype_perceptron_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_NN_prototype_perceptron_0_0 || ORIG_REF_NAME==PL_NN_prototype_perceptron_0_0} -quiet] -quiet

# IP: bd/PL_NN_prototype/ip/PL_NN_prototype_perceptron_1_0/PL_NN_prototype_perceptron_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_NN_prototype_perceptron_1_0 || ORIG_REF_NAME==PL_NN_prototype_perceptron_1_0} -quiet] -quiet

# IP: bd/PL_NN_prototype/ip/PL_NN_prototype_perceptron_2_0/PL_NN_prototype_perceptron_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_NN_prototype_perceptron_2_0 || ORIG_REF_NAME==PL_NN_prototype_perceptron_2_0} -quiet] -quiet

# IP: bd/PL_NN_prototype/ip/PL_NN_prototype_axi4_lite_final_outp_0_0/PL_NN_prototype_axi4_lite_final_outp_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_NN_prototype_axi4_lite_final_outp_0_0 || ORIG_REF_NAME==PL_NN_prototype_axi4_lite_final_outp_0_0} -quiet] -quiet

# IP: bd/PL_NN_prototype/ip/PL_NN_prototype_xlconstant_0_0/PL_NN_prototype_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_NN_prototype_xlconstant_0_0 || ORIG_REF_NAME==PL_NN_prototype_xlconstant_0_0} -quiet] -quiet

# IP: bd/PL_NN_prototype/ip/PL_NN_prototype_xlconstant_0_1/PL_NN_prototype_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_NN_prototype_xlconstant_0_1 || ORIG_REF_NAME==PL_NN_prototype_xlconstant_0_1} -quiet] -quiet

# IP: bd/PL_NN_prototype/ip/PL_NN_prototype_processing_system7_0_0/PL_NN_prototype_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_NN_prototype_processing_system7_0_0 || ORIG_REF_NAME==PL_NN_prototype_processing_system7_0_0} -quiet] -quiet

# IP: bd/PL_NN_prototype/ip/PL_NN_prototype_axi_gpio_0_0/PL_NN_prototype_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_NN_prototype_axi_gpio_0_0 || ORIG_REF_NAME==PL_NN_prototype_axi_gpio_0_0} -quiet] -quiet

# IP: bd/PL_NN_prototype/ip/PL_NN_prototype_rst_ps7_0_100M_0/PL_NN_prototype_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_NN_prototype_rst_ps7_0_100M_0 || ORIG_REF_NAME==PL_NN_prototype_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/PL_NN_prototype/ip/PL_NN_prototype_auto_pc_0/PL_NN_prototype_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_NN_prototype_auto_pc_0 || ORIG_REF_NAME==PL_NN_prototype_auto_pc_0} -quiet] -quiet

# XDC: c:/git_repos/mnist_neuralnet/fpga/source/perceptron/rtl/src/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc

# XDC: bd/PL_NN_prototype/PL_NN_prototype_ooc.xdc
