# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/weight_memory_0.xci
# IP: The module: 'weight_memory_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_DP_bram_0_0/weight_memory_DP_bram_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==weight_memory_DP_bram_0_0 || ORIG_REF_NAME==weight_memory_DP_bram_0_0} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_DP_bram_0_1/weight_memory_DP_bram_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==weight_memory_DP_bram_0_1 || ORIG_REF_NAME==weight_memory_DP_bram_0_1} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_DP_bram_0_10/weight_memory_DP_bram_0_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==weight_memory_DP_bram_0_10 || ORIG_REF_NAME==weight_memory_DP_bram_0_10} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_DP_bram_0_11/weight_memory_DP_bram_0_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==weight_memory_DP_bram_0_11 || ORIG_REF_NAME==weight_memory_DP_bram_0_11} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_DP_bram_0_12/weight_memory_DP_bram_0_12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==weight_memory_DP_bram_0_12 || ORIG_REF_NAME==weight_memory_DP_bram_0_12} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_DP_bram_0_13/weight_memory_DP_bram_0_13.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==weight_memory_DP_bram_0_13 || ORIG_REF_NAME==weight_memory_DP_bram_0_13} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_DP_bram_0_14/weight_memory_DP_bram_0_14.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==weight_memory_DP_bram_0_14 || ORIG_REF_NAME==weight_memory_DP_bram_0_14} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_DP_bram_0_15/weight_memory_DP_bram_0_15.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==weight_memory_DP_bram_0_15 || ORIG_REF_NAME==weight_memory_DP_bram_0_15} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_DP_bram_0_16/weight_memory_DP_bram_0_16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==weight_memory_DP_bram_0_16 || ORIG_REF_NAME==weight_memory_DP_bram_0_16} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_DP_bram_0_17/weight_memory_DP_bram_0_17.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==weight_memory_DP_bram_0_17 || ORIG_REF_NAME==weight_memory_DP_bram_0_17} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_DP_bram_0_18/weight_memory_DP_bram_0_18.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==weight_memory_DP_bram_0_18 || ORIG_REF_NAME==weight_memory_DP_bram_0_18} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_DP_bram_0_19/weight_memory_DP_bram_0_19.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==weight_memory_DP_bram_0_19 || ORIG_REF_NAME==weight_memory_DP_bram_0_19} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_DP_bram_0_2/weight_memory_DP_bram_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==weight_memory_DP_bram_0_2 || ORIG_REF_NAME==weight_memory_DP_bram_0_2} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_DP_bram_0_3/weight_memory_DP_bram_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==weight_memory_DP_bram_0_3 || ORIG_REF_NAME==weight_memory_DP_bram_0_3} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_DP_bram_0_4/weight_memory_DP_bram_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==weight_memory_DP_bram_0_4 || ORIG_REF_NAME==weight_memory_DP_bram_0_4} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_DP_bram_0_5/weight_memory_DP_bram_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==weight_memory_DP_bram_0_5 || ORIG_REF_NAME==weight_memory_DP_bram_0_5} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_DP_bram_0_6/weight_memory_DP_bram_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==weight_memory_DP_bram_0_6 || ORIG_REF_NAME==weight_memory_DP_bram_0_6} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_DP_bram_0_7/weight_memory_DP_bram_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==weight_memory_DP_bram_0_7 || ORIG_REF_NAME==weight_memory_DP_bram_0_7} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_DP_bram_0_8/weight_memory_DP_bram_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==weight_memory_DP_bram_0_8 || ORIG_REF_NAME==weight_memory_DP_bram_0_8} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_DP_bram_0_9/weight_memory_DP_bram_0_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==weight_memory_DP_bram_0_9 || ORIG_REF_NAME==weight_memory_DP_bram_0_9} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_xlconcat_0_0/weight_memory_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==weight_memory_xlconcat_0_0 || ORIG_REF_NAME==weight_memory_xlconcat_0_0} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_xbar_0/weight_memory_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==weight_memory_xbar_0 || ORIG_REF_NAME==weight_memory_xbar_0} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_xlconstant_0_0/weight_memory_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==weight_memory_xlconstant_0_0 || ORIG_REF_NAME==weight_memory_xlconstant_0_0} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_tier2_xbar_0_0/weight_memory_tier2_xbar_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==weight_memory_tier2_xbar_0_0 || ORIG_REF_NAME==weight_memory_tier2_xbar_0_0} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_tier2_xbar_1_0/weight_memory_tier2_xbar_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==weight_memory_tier2_xbar_1_0 || ORIG_REF_NAME==weight_memory_tier2_xbar_1_0} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_tier2_xbar_2_0/weight_memory_tier2_xbar_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==weight_memory_tier2_xbar_2_0 || ORIG_REF_NAME==weight_memory_tier2_xbar_2_0} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_auto_pc_0/weight_memory_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==weight_memory_auto_pc_0 || ORIG_REF_NAME==weight_memory_auto_pc_0} -quiet] -quiet

# XDC: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_auto_pc_0/weight_memory_auto_pc_0_ooc.xdc

# XDC: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'weight_memory_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/weight_memory_0.xci
# IP: The module: 'weight_memory_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_DP_bram_0_0/weight_memory_DP_bram_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==weight_memory_DP_bram_0_0 || ORIG_REF_NAME==weight_memory_DP_bram_0_0} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_DP_bram_0_1/weight_memory_DP_bram_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==weight_memory_DP_bram_0_1 || ORIG_REF_NAME==weight_memory_DP_bram_0_1} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_DP_bram_0_10/weight_memory_DP_bram_0_10.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==weight_memory_DP_bram_0_10 || ORIG_REF_NAME==weight_memory_DP_bram_0_10} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_DP_bram_0_11/weight_memory_DP_bram_0_11.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==weight_memory_DP_bram_0_11 || ORIG_REF_NAME==weight_memory_DP_bram_0_11} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_DP_bram_0_12/weight_memory_DP_bram_0_12.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==weight_memory_DP_bram_0_12 || ORIG_REF_NAME==weight_memory_DP_bram_0_12} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_DP_bram_0_13/weight_memory_DP_bram_0_13.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==weight_memory_DP_bram_0_13 || ORIG_REF_NAME==weight_memory_DP_bram_0_13} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_DP_bram_0_14/weight_memory_DP_bram_0_14.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==weight_memory_DP_bram_0_14 || ORIG_REF_NAME==weight_memory_DP_bram_0_14} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_DP_bram_0_15/weight_memory_DP_bram_0_15.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==weight_memory_DP_bram_0_15 || ORIG_REF_NAME==weight_memory_DP_bram_0_15} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_DP_bram_0_16/weight_memory_DP_bram_0_16.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==weight_memory_DP_bram_0_16 || ORIG_REF_NAME==weight_memory_DP_bram_0_16} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_DP_bram_0_17/weight_memory_DP_bram_0_17.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==weight_memory_DP_bram_0_17 || ORIG_REF_NAME==weight_memory_DP_bram_0_17} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_DP_bram_0_18/weight_memory_DP_bram_0_18.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==weight_memory_DP_bram_0_18 || ORIG_REF_NAME==weight_memory_DP_bram_0_18} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_DP_bram_0_19/weight_memory_DP_bram_0_19.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==weight_memory_DP_bram_0_19 || ORIG_REF_NAME==weight_memory_DP_bram_0_19} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_DP_bram_0_2/weight_memory_DP_bram_0_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==weight_memory_DP_bram_0_2 || ORIG_REF_NAME==weight_memory_DP_bram_0_2} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_DP_bram_0_3/weight_memory_DP_bram_0_3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==weight_memory_DP_bram_0_3 || ORIG_REF_NAME==weight_memory_DP_bram_0_3} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_DP_bram_0_4/weight_memory_DP_bram_0_4.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==weight_memory_DP_bram_0_4 || ORIG_REF_NAME==weight_memory_DP_bram_0_4} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_DP_bram_0_5/weight_memory_DP_bram_0_5.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==weight_memory_DP_bram_0_5 || ORIG_REF_NAME==weight_memory_DP_bram_0_5} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_DP_bram_0_6/weight_memory_DP_bram_0_6.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==weight_memory_DP_bram_0_6 || ORIG_REF_NAME==weight_memory_DP_bram_0_6} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_DP_bram_0_7/weight_memory_DP_bram_0_7.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==weight_memory_DP_bram_0_7 || ORIG_REF_NAME==weight_memory_DP_bram_0_7} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_DP_bram_0_8/weight_memory_DP_bram_0_8.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==weight_memory_DP_bram_0_8 || ORIG_REF_NAME==weight_memory_DP_bram_0_8} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_DP_bram_0_9/weight_memory_DP_bram_0_9.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==weight_memory_DP_bram_0_9 || ORIG_REF_NAME==weight_memory_DP_bram_0_9} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_xlconcat_0_0/weight_memory_xlconcat_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==weight_memory_xlconcat_0_0 || ORIG_REF_NAME==weight_memory_xlconcat_0_0} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_xbar_0/weight_memory_xbar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==weight_memory_xbar_0 || ORIG_REF_NAME==weight_memory_xbar_0} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_xlconstant_0_0/weight_memory_xlconstant_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==weight_memory_xlconstant_0_0 || ORIG_REF_NAME==weight_memory_xlconstant_0_0} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_tier2_xbar_0_0/weight_memory_tier2_xbar_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==weight_memory_tier2_xbar_0_0 || ORIG_REF_NAME==weight_memory_tier2_xbar_0_0} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_tier2_xbar_1_0/weight_memory_tier2_xbar_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==weight_memory_tier2_xbar_1_0 || ORIG_REF_NAME==weight_memory_tier2_xbar_1_0} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_tier2_xbar_2_0/weight_memory_tier2_xbar_2_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==weight_memory_tier2_xbar_2_0 || ORIG_REF_NAME==weight_memory_tier2_xbar_2_0} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_auto_pc_0/weight_memory_auto_pc_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==weight_memory_auto_pc_0 || ORIG_REF_NAME==weight_memory_auto_pc_0} -quiet] -quiet

# XDC: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_auto_pc_0/weight_memory_auto_pc_0_ooc.xdc

# XDC: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/MemoryManager/MemoryManager.srcs/sources_1/ip/weight_memory_0/src/weight_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'weight_memory_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
