# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/layer_0/layer_0.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==layer_0 || ORIG_REF_NAME==layer_0} -quiet] -quiet

# IP: bd/layer_0/ip/layer_0_perceptron_0_0/layer_0_perceptron_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==layer_0_perceptron_0_0 || ORIG_REF_NAME==layer_0_perceptron_0_0} -quiet] -quiet

# IP: bd/layer_0/ip/layer_0_perceptron_0_1/layer_0_perceptron_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==layer_0_perceptron_0_1 || ORIG_REF_NAME==layer_0_perceptron_0_1} -quiet] -quiet

# IP: bd/layer_0/ip/layer_0_perceptron_0_2/layer_0_perceptron_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==layer_0_perceptron_0_2 || ORIG_REF_NAME==layer_0_perceptron_0_2} -quiet] -quiet

# IP: bd/layer_0/ip/layer_0_axi4_lite_register_m_0_0/layer_0_axi4_lite_register_m_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==layer_0_axi4_lite_register_m_0_0 || ORIG_REF_NAME==layer_0_axi4_lite_register_m_0_0} -quiet] -quiet

# IP: bd/layer_0/ip/layer_0_xbar_0/layer_0_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==layer_0_xbar_0 || ORIG_REF_NAME==layer_0_xbar_0} -quiet] -quiet

# IP: bd/layer_0/ip/layer_0_axi_interconnect_0_0/layer_0_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==layer_0_axi_interconnect_0_0 || ORIG_REF_NAME==layer_0_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/layer_0/ip/layer_0_axis_broadcaster_0_0/layer_0_axis_broadcaster_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==layer_0_axis_broadcaster_0_0 || ORIG_REF_NAME==layer_0_axis_broadcaster_0_0} -quiet] -quiet

# IP: bd/layer_0/ip/layer_0_image_loader_module_0_0/layer_0_image_loader_module_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==layer_0_image_loader_module_0_0 || ORIG_REF_NAME==layer_0_image_loader_module_0_0} -quiet] -quiet

# IP: bd/layer_0/ip/layer_0_axi4_lite_layer_conn_0_0/layer_0_axi4_lite_layer_conn_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==layer_0_axi4_lite_layer_conn_0_0 || ORIG_REF_NAME==layer_0_axi4_lite_layer_conn_0_0} -quiet] -quiet

# IP: bd/layer_0/ip/layer_0_auto_pc_0/layer_0_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==layer_0_auto_pc_0 || ORIG_REF_NAME==layer_0_auto_pc_0} -quiet] -quiet

# XDC: bd/layer_0/layer_0_ooc.xdc
