# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/git_repos/mnist_neuralnet/fpga/8_26_2024_validating_on_zybo_v1/8_26_2024_validating_on_zybo_v1.cache/wt [current_project]
set_property parent.project_path C:/git_repos/mnist_neuralnet/fpga/8_26_2024_validating_on_zybo_v1/8_26_2024_validating_on_zybo_v1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:2.0 [current_project]
set_property ip_repo_paths {
  c:/git_repos/mnist_neuralnet/fpga/source/dual_port_AXI_Native_bram/rtl
  c:/git_repos/mnist_neuralnet/fpga/source/image_loader_module/rtl
  c:/git_repos/mnist_neuralnet/fpga/source/axi4_lite_layer_connector/rtl
  c:/git_repos/mnist_neuralnet/fpga/source/axi4_lite_register_module/rtl
  c:/git_repos/mnist_neuralnet/fpga/source/perceptron/rtl
} [current_project]
update_ip_catalog
set_property ip_output_repo c:/git_repos/mnist_neuralnet/fpga/8_26_2024_validating_on_zybo_v1/8_26_2024_validating_on_zybo_v1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/git_repos/mnist_neuralnet/fpga/8_26_2024_validating_on_zybo_v1/w_0_0.coe
read_verilog -library xil_defaultlib C:/git_repos/mnist_neuralnet/fpga/8_26_2024_validating_on_zybo_v1/8_26_2024_validating_on_zybo_v1.srcs/sources_1/bd/layer_0/hdl/layer_0_wrapper.v
add_files C:/git_repos/mnist_neuralnet/fpga/8_26_2024_validating_on_zybo_v1/8_26_2024_validating_on_zybo_v1.srcs/sources_1/bd/layer_0/layer_0.bd
set_property used_in_implementation false [get_files -all c:/git_repos/mnist_neuralnet/fpga/8_26_2024_validating_on_zybo_v1/8_26_2024_validating_on_zybo_v1.srcs/sources_1/bd/layer_0/ip/layer_0_xbar_0/layer_0_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/git_repos/mnist_neuralnet/fpga/8_26_2024_validating_on_zybo_v1/8_26_2024_validating_on_zybo_v1.srcs/sources_1/bd/layer_0/ip/layer_0_axis_broadcaster_0_0/layer_0_axis_broadcaster_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/git_repos/mnist_neuralnet/fpga/8_26_2024_validating_on_zybo_v1/8_26_2024_validating_on_zybo_v1.srcs/sources_1/bd/layer_0/ip/layer_0_auto_pc_0/layer_0_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/git_repos/mnist_neuralnet/fpga/8_26_2024_validating_on_zybo_v1/8_26_2024_validating_on_zybo_v1.srcs/sources_1/bd/layer_0/layer_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top layer_0_wrapper -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef layer_0_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file layer_0_wrapper_utilization_synth.rpt -pb layer_0_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
