# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/DP_PL_PS_BRAM/DP_PL_PS_BRAM.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DP_PL_PS_BRAM || ORIG_REF_NAME==DP_PL_PS_BRAM} -quiet] -quiet

# IP: bd/DP_PL_PS_BRAM/ip/DP_PL_PS_BRAM_axi_bram_ctrl_0_0/DP_PL_PS_BRAM_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DP_PL_PS_BRAM_axi_bram_ctrl_0_0 || ORIG_REF_NAME==DP_PL_PS_BRAM_axi_bram_ctrl_0_0} -quiet] -quiet

# XDC: bd/DP_PL_PS_BRAM/DP_PL_PS_BRAM_ooc.xdc
