# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/git_repos/mnist_neuralnet/fpga/projects/9_18/9_18.srcs/sources_1/bd/PL_NN_prototype/ip/PL_NN_prototype_axi_gpio_0_0/PL_NN_prototype_axi_gpio_0_0.xci
# IP: The module: 'PL_NN_prototype_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/git_repos/mnist_neuralnet/fpga/projects/9_18/9_18.srcs/sources_1/bd/PL_NN_prototype/ip/PL_NN_prototype_axi_gpio_0_0/PL_NN_prototype_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PL_NN_prototype_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/git_repos/mnist_neuralnet/fpga/projects/9_18/9_18.srcs/sources_1/bd/PL_NN_prototype/ip/PL_NN_prototype_axi_gpio_0_0/PL_NN_prototype_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PL_NN_prototype_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/git_repos/mnist_neuralnet/fpga/projects/9_18/9_18.srcs/sources_1/bd/PL_NN_prototype/ip/PL_NN_prototype_axi_gpio_0_0/PL_NN_prototype_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'PL_NN_prototype_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/projects/9_18/9_18.srcs/sources_1/bd/PL_NN_prototype/ip/PL_NN_prototype_axi_gpio_0_0/PL_NN_prototype_axi_gpio_0_0.xci
# IP: The module: 'PL_NN_prototype_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/git_repos/mnist_neuralnet/fpga/projects/9_18/9_18.srcs/sources_1/bd/PL_NN_prototype/ip/PL_NN_prototype_axi_gpio_0_0/PL_NN_prototype_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PL_NN_prototype_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/git_repos/mnist_neuralnet/fpga/projects/9_18/9_18.srcs/sources_1/bd/PL_NN_prototype/ip/PL_NN_prototype_axi_gpio_0_0/PL_NN_prototype_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PL_NN_prototype_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/git_repos/mnist_neuralnet/fpga/projects/9_18/9_18.srcs/sources_1/bd/PL_NN_prototype/ip/PL_NN_prototype_axi_gpio_0_0/PL_NN_prototype_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'PL_NN_prototype_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
