# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/git_repos/mnist_neuralnet/fpga/milestone2/projects/DP_bram/DP_bram.srcs/sources_1/bd/axi_bram_block/ip/axi_bram_block_DP_bram_6_0/axi_bram_block_DP_bram_6_0.xci
# IP: The module: 'axi_bram_block_DP_bram_6_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/DP_bram/DP_bram.srcs/sources_1/bd/axi_bram_block/ip/src/blk_mem_gen_0/blk_mem_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/DP_bram/DP_bram.srcs/sources_1/bd/axi_bram_block/ip/src/axi_bram_ctrl_0/axi_bram_ctrl_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_bram_ctrl_0 || ORIG_REF_NAME==axi_bram_ctrl_0} -quiet] -quiet

# XDC: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/DP_bram/DP_bram.srcs/sources_1/bd/axi_bram_block/ip/src/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc

# IP: C:/git_repos/mnist_neuralnet/fpga/milestone2/projects/DP_bram/DP_bram.srcs/sources_1/bd/axi_bram_block/ip/axi_bram_block_DP_bram_6_0/axi_bram_block_DP_bram_6_0.xci
# IP: The module: 'axi_bram_block_DP_bram_6_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/DP_bram/DP_bram.srcs/sources_1/bd/axi_bram_block/ip/src/blk_mem_gen_0/blk_mem_gen_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/DP_bram/DP_bram.srcs/sources_1/bd/axi_bram_block/ip/src/axi_bram_ctrl_0/axi_bram_ctrl_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_bram_ctrl_0 || ORIG_REF_NAME==axi_bram_ctrl_0} -quiet] -quiet

# XDC: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/DP_bram/DP_bram.srcs/sources_1/bd/axi_bram_block/ip/src/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc
