# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/DMA_test/DMA_test.srcs/sources_1/bd/design_2/ip/design_2_blk_mem_gen_0_0/design_2_blk_mem_gen_0_0.xci
# IP: The module: 'design_2_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/DMA_test/DMA_test.srcs/sources_1/bd/design_2/ip/design_2_blk_mem_gen_0_0/design_2_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/DMA_test/DMA_test.srcs/sources_1/bd/design_2/ip/design_2_blk_mem_gen_0_0/design_2_blk_mem_gen_0_0.xci
# IP: The module: 'design_2_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/DMA_test/DMA_test.srcs/sources_1/bd/design_2/ip/design_2_blk_mem_gen_0_0/design_2_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
