# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/zynq_only/zynq_only.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_only || ORIG_REF_NAME==zynq_only} -quiet] -quiet

# IP: bd/zynq_only/ip/zynq_only_processing_system7_0_0/zynq_only_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_only_processing_system7_0_0 || ORIG_REF_NAME==zynq_only_processing_system7_0_0} -quiet] -quiet

# XDC: bd/zynq_only/zynq_only_ooc.xdc
