# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_smartconnect_0_0/zynq7000_preset_smartconnect_0_0.xci
# IP: The module: 'zynq7000_preset_smartconnect_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_smartconnect_0_0/bd_0/bd_6739.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_smartconnect_0_0/bd_0/ip/ip_0/bd_6739_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_smartconnect_0_0/bd_0/ip/ip_1/bd_6739_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_smartconnect_0_0/bd_0/ip/ip_2/bd_6739_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_smartconnect_0_0/bd_0/ip/ip_3/bd_6739_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_smartconnect_0_0/bd_0/ip/ip_4/bd_6739_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_smartconnect_0_0/bd_0/ip/ip_5/bd_6739_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_smartconnect_0_0/bd_0/ip/ip_6/bd_6739_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_smartconnect_0_0/bd_0/ip/ip_7/bd_6739_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_smartconnect_0_0/bd_0/ip/ip_8/bd_6739_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_smartconnect_0_0/bd_0/ip/ip_9/bd_6739_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_smartconnect_0_0/bd_0/ip/ip_10/bd_6739_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_smartconnect_0_0/bd_0/ip/ip_11/bd_6739_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_smartconnect_0_0/bd_0/ip/ip_12/bd_6739_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_smartconnect_0_0/bd_0/ip/ip_1/bd_6739_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_smartconnect_0_0/bd_0/ip/ip_1/bd_6739_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_smartconnect_0_0/bd_0/ip/ip_5/bd_6739_s00a2s_0_ooc.xdc

# XDC: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_smartconnect_0_0/bd_0/ip/ip_6/bd_6739_sarn_0_ooc.xdc

# XDC: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_smartconnect_0_0/bd_0/ip/ip_7/bd_6739_srn_0_ooc.xdc

# XDC: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_smartconnect_0_0/bd_0/ip/ip_8/bd_6739_sawn_0_ooc.xdc

# XDC: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_smartconnect_0_0/bd_0/ip/ip_9/bd_6739_swn_0_ooc.xdc

# XDC: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_smartconnect_0_0/bd_0/ip/ip_10/bd_6739_sbn_0_ooc.xdc

# XDC: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_smartconnect_0_0/bd_0/ip/ip_11/bd_6739_m00s2a_0_ooc.xdc

# XDC: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_smartconnect_0_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq7000_preset_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_smartconnect_0_0/zynq7000_preset_smartconnect_0_0.xci
# IP: The module: 'zynq7000_preset_smartconnect_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_smartconnect_0_0/bd_0/bd_6739.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_smartconnect_0_0/bd_0/ip/ip_0/bd_6739_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_smartconnect_0_0/bd_0/ip/ip_1/bd_6739_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_smartconnect_0_0/bd_0/ip/ip_2/bd_6739_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_smartconnect_0_0/bd_0/ip/ip_3/bd_6739_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_smartconnect_0_0/bd_0/ip/ip_4/bd_6739_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_smartconnect_0_0/bd_0/ip/ip_5/bd_6739_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_smartconnect_0_0/bd_0/ip/ip_6/bd_6739_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_smartconnect_0_0/bd_0/ip/ip_7/bd_6739_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_smartconnect_0_0/bd_0/ip/ip_8/bd_6739_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_smartconnect_0_0/bd_0/ip/ip_9/bd_6739_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_smartconnect_0_0/bd_0/ip/ip_10/bd_6739_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_smartconnect_0_0/bd_0/ip/ip_11/bd_6739_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_smartconnect_0_0/bd_0/ip/ip_12/bd_6739_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_smartconnect_0_0/bd_0/ip/ip_1/bd_6739_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_smartconnect_0_0/bd_0/ip/ip_1/bd_6739_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_smartconnect_0_0/bd_0/ip/ip_5/bd_6739_s00a2s_0_ooc.xdc

# XDC: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_smartconnect_0_0/bd_0/ip/ip_6/bd_6739_sarn_0_ooc.xdc

# XDC: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_smartconnect_0_0/bd_0/ip/ip_7/bd_6739_srn_0_ooc.xdc

# XDC: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_smartconnect_0_0/bd_0/ip/ip_8/bd_6739_sawn_0_ooc.xdc

# XDC: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_smartconnect_0_0/bd_0/ip/ip_9/bd_6739_swn_0_ooc.xdc

# XDC: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_smartconnect_0_0/bd_0/ip/ip_10/bd_6739_sbn_0_ooc.xdc

# XDC: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_smartconnect_0_0/bd_0/ip/ip_11/bd_6739_m00s2a_0_ooc.xdc

# XDC: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_smartconnect_0_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq7000_preset_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
