# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/PL_NN/PL_NN.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_NN || ORIG_REF_NAME==PL_NN} -quiet] -quiet

# IP: bd/PL_NN/ip/PL_NN_processing_system7_0_0/PL_NN_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_NN_processing_system7_0_0 || ORIG_REF_NAME==PL_NN_processing_system7_0_0} -quiet] -quiet

# IP: bd/PL_NN/ip/PL_NN_proc_sys_reset_0_0/PL_NN_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_NN_proc_sys_reset_0_0 || ORIG_REF_NAME==PL_NN_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/PL_NN/ip/PL_NN_axi4_lite_register_m_0_0/PL_NN_axi4_lite_register_m_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_NN_axi4_lite_register_m_0_0 || ORIG_REF_NAME==PL_NN_axi4_lite_register_m_0_0} -quiet] -quiet

# IP: bd/PL_NN/ip/PL_NN_xbar_0/PL_NN_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_NN_xbar_0 || ORIG_REF_NAME==PL_NN_xbar_0} -quiet] -quiet

# IP: bd/PL_NN/ip/PL_NN_axi_interconnect_0_0/PL_NN_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_NN_axi_interconnect_0_0 || ORIG_REF_NAME==PL_NN_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/PL_NN/ip/PL_NN_perceptron_0_0/PL_NN_perceptron_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_NN_perceptron_0_0 || ORIG_REF_NAME==PL_NN_perceptron_0_0} -quiet] -quiet

# IP: bd/PL_NN/ip/PL_NN_perceptron_0_1/PL_NN_perceptron_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_NN_perceptron_0_1 || ORIG_REF_NAME==PL_NN_perceptron_0_1} -quiet] -quiet

# IP: bd/PL_NN/ip/PL_NN_perceptron_0_2/PL_NN_perceptron_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_NN_perceptron_0_2 || ORIG_REF_NAME==PL_NN_perceptron_0_2} -quiet] -quiet

# IP: bd/PL_NN/ip/PL_NN_perceptron_0_3/PL_NN_perceptron_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_NN_perceptron_0_3 || ORIG_REF_NAME==PL_NN_perceptron_0_3} -quiet] -quiet

# IP: bd/PL_NN/ip/PL_NN_perceptron_0_4/PL_NN_perceptron_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_NN_perceptron_0_4 || ORIG_REF_NAME==PL_NN_perceptron_0_4} -quiet] -quiet

# IP: bd/PL_NN/ip/PL_NN_perceptron_0_5/PL_NN_perceptron_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_NN_perceptron_0_5 || ORIG_REF_NAME==PL_NN_perceptron_0_5} -quiet] -quiet

# IP: bd/PL_NN/ip/PL_NN_perceptron_0_6/PL_NN_perceptron_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_NN_perceptron_0_6 || ORIG_REF_NAME==PL_NN_perceptron_0_6} -quiet] -quiet

# IP: bd/PL_NN/ip/PL_NN_perceptron_0_7/PL_NN_perceptron_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_NN_perceptron_0_7 || ORIG_REF_NAME==PL_NN_perceptron_0_7} -quiet] -quiet

# IP: bd/PL_NN/ip/PL_NN_perceptron_0_8/PL_NN_perceptron_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_NN_perceptron_0_8 || ORIG_REF_NAME==PL_NN_perceptron_0_8} -quiet] -quiet

# IP: bd/PL_NN/ip/PL_NN_perceptron_0_9/PL_NN_perceptron_0_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_NN_perceptron_0_9 || ORIG_REF_NAME==PL_NN_perceptron_0_9} -quiet] -quiet

# IP: bd/PL_NN/ip/PL_NN_axi4_lite_layer_conn_0_0/PL_NN_axi4_lite_layer_conn_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_NN_axi4_lite_layer_conn_0_0 || ORIG_REF_NAME==PL_NN_axi4_lite_layer_conn_0_0} -quiet] -quiet

# IP: bd/PL_NN/ip/PL_NN_perceptron_0_18/PL_NN_perceptron_0_18.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_NN_perceptron_0_18 || ORIG_REF_NAME==PL_NN_perceptron_0_18} -quiet] -quiet

# IP: bd/PL_NN/ip/PL_NN_perceptron_1_0/PL_NN_perceptron_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_NN_perceptron_1_0 || ORIG_REF_NAME==PL_NN_perceptron_1_0} -quiet] -quiet

# IP: bd/PL_NN/ip/PL_NN_perceptron_2_0/PL_NN_perceptron_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_NN_perceptron_2_0 || ORIG_REF_NAME==PL_NN_perceptron_2_0} -quiet] -quiet

# IP: bd/PL_NN/ip/PL_NN_perceptron_3_0/PL_NN_perceptron_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_NN_perceptron_3_0 || ORIG_REF_NAME==PL_NN_perceptron_3_0} -quiet] -quiet

# IP: bd/PL_NN/ip/PL_NN_perceptron_4_0/PL_NN_perceptron_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_NN_perceptron_4_0 || ORIG_REF_NAME==PL_NN_perceptron_4_0} -quiet] -quiet

# IP: bd/PL_NN/ip/PL_NN_perceptron_5_0/PL_NN_perceptron_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_NN_perceptron_5_0 || ORIG_REF_NAME==PL_NN_perceptron_5_0} -quiet] -quiet

# IP: bd/PL_NN/ip/PL_NN_perceptron_6_0/PL_NN_perceptron_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_NN_perceptron_6_0 || ORIG_REF_NAME==PL_NN_perceptron_6_0} -quiet] -quiet

# IP: bd/PL_NN/ip/PL_NN_perceptron_7_0/PL_NN_perceptron_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_NN_perceptron_7_0 || ORIG_REF_NAME==PL_NN_perceptron_7_0} -quiet] -quiet

# IP: bd/PL_NN/ip/PL_NN_perceptron_8_0/PL_NN_perceptron_8_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_NN_perceptron_8_0 || ORIG_REF_NAME==PL_NN_perceptron_8_0} -quiet] -quiet

# IP: bd/PL_NN/ip/PL_NN_perceptron_9_0/PL_NN_perceptron_9_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_NN_perceptron_9_0 || ORIG_REF_NAME==PL_NN_perceptron_9_0} -quiet] -quiet

# IP: bd/PL_NN/ip/PL_NN_image_loader_module_0_0/PL_NN_image_loader_module_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_NN_image_loader_module_0_0 || ORIG_REF_NAME==PL_NN_image_loader_module_0_0} -quiet] -quiet

# IP: bd/PL_NN/ip/PL_NN_axi4_lite_final_outp_0_0/PL_NN_axi4_lite_final_outp_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_NN_axi4_lite_final_outp_0_0 || ORIG_REF_NAME==PL_NN_axi4_lite_final_outp_0_0} -quiet] -quiet

# IP: bd/PL_NN/ip/PL_NN_hardmax_0_0/PL_NN_hardmax_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_NN_hardmax_0_0 || ORIG_REF_NAME==PL_NN_hardmax_0_0} -quiet] -quiet

# IP: bd/PL_NN/ip/PL_NN_axis_broadcaster_0_0/PL_NN_axis_broadcaster_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_NN_axis_broadcaster_0_0 || ORIG_REF_NAME==PL_NN_axis_broadcaster_0_0} -quiet] -quiet

# IP: bd/PL_NN/ip/PL_NN_axi_gpio_0_0/PL_NN_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_NN_axi_gpio_0_0 || ORIG_REF_NAME==PL_NN_axi_gpio_0_0} -quiet] -quiet

# IP: bd/PL_NN/ip/PL_NN_axi_gpio_0_1/PL_NN_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_NN_axi_gpio_0_1 || ORIG_REF_NAME==PL_NN_axi_gpio_0_1} -quiet] -quiet

# IP: bd/PL_NN/ip/PL_NN_axis_broadcaster_2_0/PL_NN_axis_broadcaster_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_NN_axis_broadcaster_2_0 || ORIG_REF_NAME==PL_NN_axis_broadcaster_2_0} -quiet] -quiet

# IP: bd/PL_NN/ip/PL_NN_tier2_xbar_0_0/PL_NN_tier2_xbar_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_NN_tier2_xbar_0_0 || ORIG_REF_NAME==PL_NN_tier2_xbar_0_0} -quiet] -quiet

# IP: bd/PL_NN/ip/PL_NN_tier2_xbar_1_0/PL_NN_tier2_xbar_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_NN_tier2_xbar_1_0 || ORIG_REF_NAME==PL_NN_tier2_xbar_1_0} -quiet] -quiet

# IP: bd/PL_NN/ip/PL_NN_tier2_xbar_2_0/PL_NN_tier2_xbar_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_NN_tier2_xbar_2_0 || ORIG_REF_NAME==PL_NN_tier2_xbar_2_0} -quiet] -quiet

# IP: bd/PL_NN/ip/PL_NN_tier2_xbar_3_0/PL_NN_tier2_xbar_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_NN_tier2_xbar_3_0 || ORIG_REF_NAME==PL_NN_tier2_xbar_3_0} -quiet] -quiet

# IP: bd/PL_NN/ip/PL_NN_auto_pc_0/PL_NN_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_NN_auto_pc_0 || ORIG_REF_NAME==PL_NN_auto_pc_0} -quiet] -quiet

# XDC: bd/PL_NN/PL_NN_ooc.xdc
