# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_ila_0_0/zynq7000_preset_ila_0_0.xci
# IP: The module: 'zynq7000_preset_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq7000_preset_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_ila_0_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq7000_preset_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_ila_0_0/zynq7000_preset_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq7000_preset_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_ila_0_0/zynq7000_preset_ila_0_0.xci
# IP: The module: 'zynq7000_preset_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq7000_preset_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_ila_0_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq7000_preset_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/zynq_example_dad/project_1/project_1.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_ila_0_0/zynq7000_preset_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq7000_preset_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
