# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/git_repos/mnist_neuralnet/fpga/8_26_2024_validating_on_zybo_v1/8_26_2024_validating_on_zybo_v1.srcs/sources_1/bd/layer_0/ip/layer_0_axis_broadcaster_0_0/layer_0_axis_broadcaster_0_0.xci
# IP: The module: 'layer_0_axis_broadcaster_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/git_repos/mnist_neuralnet/fpga/8_26_2024_validating_on_zybo_v1/8_26_2024_validating_on_zybo_v1.srcs/sources_1/bd/layer_0/ip/layer_0_axis_broadcaster_0_0/layer_0_axis_broadcaster_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'layer_0_axis_broadcaster_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/git_repos/mnist_neuralnet/fpga/8_26_2024_validating_on_zybo_v1/8_26_2024_validating_on_zybo_v1.srcs/sources_1/bd/layer_0/ip/layer_0_axis_broadcaster_0_0/layer_0_axis_broadcaster_0_0.xci
# IP: The module: 'layer_0_axis_broadcaster_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/git_repos/mnist_neuralnet/fpga/8_26_2024_validating_on_zybo_v1/8_26_2024_validating_on_zybo_v1.srcs/sources_1/bd/layer_0/ip/layer_0_axis_broadcaster_0_0/layer_0_axis_broadcaster_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'layer_0_axis_broadcaster_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
