# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/git_repos/mnist_neuralnet/fpga/projects/9_18/9_18.srcs/sources_1/bd/PL_NN/ip/PL_NN_axis_broadcaster_0_2/PL_NN_axis_broadcaster_0_2.xci
# IP: The module: 'PL_NN_axis_broadcaster_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/git_repos/mnist_neuralnet/fpga/projects/9_18/9_18.srcs/sources_1/bd/PL_NN/ip/PL_NN_axis_broadcaster_0_2/PL_NN_axis_broadcaster_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PL_NN_axis_broadcaster_0_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/git_repos/mnist_neuralnet/fpga/projects/9_18/9_18.srcs/sources_1/bd/PL_NN/ip/PL_NN_axis_broadcaster_0_2/PL_NN_axis_broadcaster_0_2.xci
# IP: The module: 'PL_NN_axis_broadcaster_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/git_repos/mnist_neuralnet/fpga/projects/9_18/9_18.srcs/sources_1/bd/PL_NN/ip/PL_NN_axis_broadcaster_0_2/PL_NN_axis_broadcaster_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PL_NN_axis_broadcaster_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
