# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/git_repos/mnist_neuralnet/fpga/projects/10_9/10_9.srcs/sources_1/bd/design_1/ip/design_1_perceptron_2_0/design_1_perceptron_2_0.xci
# IP: The module: 'design_1_perceptron_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/git_repos/mnist_neuralnet/fpga/projects/10_9/10_9.srcs/sources_1/bd/design_1/ip/design_1_perceptron_2_0/src/ila_0/ila_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/projects/10_9/10_9.srcs/sources_1/bd/design_1/ip/design_1_perceptron_2_0/src/mult_gen_0/mult_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_gen_0 || ORIG_REF_NAME==mult_gen_0} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/projects/10_9/10_9.srcs/sources_1/bd/design_1/ip/design_1_perceptron_2_0/src/blk_mem_gen_0/blk_mem_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/projects/10_9/10_9.srcs/sources_1/bd/design_1/ip/design_1_perceptron_2_0/src/axi_bram_ctrl_0/axi_bram_ctrl_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_bram_ctrl_0 || ORIG_REF_NAME==axi_bram_ctrl_0} -quiet] -quiet

# XDC: c:/git_repos/mnist_neuralnet/fpga/projects/10_9/10_9.srcs/sources_1/bd/design_1/ip/design_1_perceptron_2_0/src/ila_0/ila_v6_2/constraints/ila.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/git_repos/mnist_neuralnet/fpga/projects/10_9/10_9.srcs/sources_1/bd/design_1/ip/design_1_perceptron_2_0/src/ila_0/ila_0_ooc.xdc

# XDC: c:/git_repos/mnist_neuralnet/fpga/projects/10_9/10_9.srcs/sources_1/bd/design_1/ip/design_1_perceptron_2_0/src/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc

# IP: C:/git_repos/mnist_neuralnet/fpga/projects/10_9/10_9.srcs/sources_1/bd/design_1/ip/design_1_perceptron_2_0/design_1_perceptron_2_0.xci
# IP: The module: 'design_1_perceptron_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/git_repos/mnist_neuralnet/fpga/projects/10_9/10_9.srcs/sources_1/bd/design_1/ip/design_1_perceptron_2_0/src/ila_0/ila_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/projects/10_9/10_9.srcs/sources_1/bd/design_1/ip/design_1_perceptron_2_0/src/mult_gen_0/mult_gen_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_gen_0 || ORIG_REF_NAME==mult_gen_0} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/projects/10_9/10_9.srcs/sources_1/bd/design_1/ip/design_1_perceptron_2_0/src/blk_mem_gen_0/blk_mem_gen_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/projects/10_9/10_9.srcs/sources_1/bd/design_1/ip/design_1_perceptron_2_0/src/axi_bram_ctrl_0/axi_bram_ctrl_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_bram_ctrl_0 || ORIG_REF_NAME==axi_bram_ctrl_0} -quiet] -quiet

# XDC: c:/git_repos/mnist_neuralnet/fpga/projects/10_9/10_9.srcs/sources_1/bd/design_1/ip/design_1_perceptron_2_0/src/ila_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/git_repos/mnist_neuralnet/fpga/projects/10_9/10_9.srcs/sources_1/bd/design_1/ip/design_1_perceptron_2_0/src/ila_0/ila_0_ooc.xdc

# XDC: c:/git_repos/mnist_neuralnet/fpga/projects/10_9/10_9.srcs/sources_1/bd/design_1/ip/design_1_perceptron_2_0/src/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc
