webtalk_init -webtalk_dir C:\\git_repos\\mnist_neuralnet\\fpga\\05_011_2024_write_to_ddr\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2024-08-23 15:14:16" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "Vitis v2019.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2019.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "212970010_0_0_848" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "Vitis" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "b15kkeuri2ae6srehn8qrldhb6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2019.2_26" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "26" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1992 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.941 GB" -context "user_environment"
webtalk_register_client -client vitis
webtalk_add_data -client vitis -key uid -value "1724451014798" -context "vitis\\\\platform/1724451014798"
webtalk_add_data -client vitis -key platform_source -value "dsa" -context "vitis\\\\platform/1724451014798"
webtalk_add_data -client vitis -key os -value "standalone" -context "vitis\\\\platform/1724451014798"
webtalk_add_data -client vitis -key processor -value "ps7_cortexa9" -context "vitis\\\\platform/1724451014798"
webtalk_add_data -client vitis -key platform -value "NA" -context "vitis\\\\platform/1724451014798"
webtalk_transmit -clientid 295990135 -regid "212970010_0_0_848" -xml C:\\git_repos\\mnist_neuralnet\\fpga\\05_011_2024_write_to_ddr\\webtalk\\usage_statistics_ext_vitis.xml -html C:\\git_repos\\mnist_neuralnet\\fpga\\05_011_2024_write_to_ddr\\webtalk\\usage_statistics_ext_vitis.html -wdm C:\\git_repos\\mnist_neuralnet\\fpga\\05_011_2024_write_to_ddr\\webtalk\\vitis_webtalk.wdm -intro "<H3>Vitis Usage Report</H3><BR>"
webtalk_terminate
