@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Sep 11 12:03:02 -0700 2024
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim image_loader_module_dad_behav -key {Behavioral:sim_1:Functional:image_loader_module_dad} -tclbatch image_loader_module_dad.tcl -protoinst "protoinst_files/DP_PL_PS_BRAM.protoinst" -protoinst "protoinst_files/DP_Weight_Memory.protoinst" -view C:/git_repos/mnist_neuralnet/fpga/8_26_2024_validating_on_zybo_v1/image_loader_module_dad_behav.wcfg -log simulate.log"
call xsim  image_loader_module_dad_behav -key {Behavioral:sim_1:Functional:image_loader_module_dad} -tclbatch image_loader_module_dad.tcl -protoinst "protoinst_files/DP_PL_PS_BRAM.protoinst" -protoinst "protoinst_files/DP_Weight_Memory.protoinst" -view C:/git_repos/mnist_neuralnet/fpga/8_26_2024_validating_on_zybo_v1/image_loader_module_dad_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
