# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/layer/layer.srcs/sources_1/ip/classifier_0/classifier_0.xci
# IP: The module: 'classifier_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/layer/layer.srcs/sources_1/ip/classifier_0/src/c_accum_1/c_accum_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_accum_1 || ORIG_REF_NAME==c_accum_1} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/layer/layer.srcs/sources_1/ip/classifier_0/src/mult_gen_0/mult_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_gen_0 || ORIG_REF_NAME==mult_gen_0} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/layer/layer.srcs/sources_1/ip/classifier_0/classifier_0.xci
# IP: The module: 'classifier_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/layer/layer.srcs/sources_1/ip/classifier_0/src/c_accum_1/c_accum_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_accum_1 || ORIG_REF_NAME==c_accum_1} -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/layer/layer.srcs/sources_1/ip/classifier_0/src/mult_gen_0/mult_gen_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_gen_0 || ORIG_REF_NAME==mult_gen_0} -quiet] -quiet
