# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/Zynq_C_imp/Standalone_Zynq/Standalone_Zynq.srcs/sources_1/bd/zynq_only/ip/zynq_only_processing_system7_0_0/zynq_only_processing_system7_0_0.xci
# IP: The module: 'zynq_only_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/Zynq_C_imp/Standalone_Zynq/Standalone_Zynq.srcs/sources_1/bd/zynq_only/ip/zynq_only_processing_system7_0_0/zynq_only_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_only_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/Zynq_C_imp/Standalone_Zynq/Standalone_Zynq.srcs/sources_1/bd/zynq_only/ip/zynq_only_processing_system7_0_0/zynq_only_processing_system7_0_0.xci
# IP: The module: 'zynq_only_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/miles/Projects/fpga/mnist_neuralnet/prototype/Zynq_C_imp/Standalone_Zynq/Standalone_Zynq.srcs/sources_1/bd/zynq_only/ip/zynq_only_processing_system7_0_0/zynq_only_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_only_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
