# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/git_repos/mnist_neuralnet/fpga/5_18_dmagithub/Vivado/zedboard_axi_dma/zedboard_axi_dma.srcs/sources_1/bd/zedboard_axi_dma/ip/zedboard_axi_dma_auto_us_2/zedboard_axi_dma_auto_us_2.xci
# IP: The module: 'zedboard_axi_dma_auto_us_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/git_repos/mnist_neuralnet/fpga/5_18_dmagithub/Vivado/zedboard_axi_dma/zedboard_axi_dma.srcs/sources_1/bd/zedboard_axi_dma/ip/zedboard_axi_dma_auto_us_2/zedboard_axi_dma_auto_us_2_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'zedboard_axi_dma_auto_us_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/git_repos/mnist_neuralnet/fpga/5_18_dmagithub/Vivado/zedboard_axi_dma/zedboard_axi_dma.srcs/sources_1/bd/zedboard_axi_dma/ip/zedboard_axi_dma_auto_us_2/zedboard_axi_dma_auto_us_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zedboard_axi_dma_auto_us_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/git_repos/mnist_neuralnet/fpga/5_18_dmagithub/Vivado/zedboard_axi_dma/zedboard_axi_dma.srcs/sources_1/bd/zedboard_axi_dma/ip/zedboard_axi_dma_auto_us_2/zedboard_axi_dma_auto_us_2.xci
# IP: The module: 'zedboard_axi_dma_auto_us_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/git_repos/mnist_neuralnet/fpga/5_18_dmagithub/Vivado/zedboard_axi_dma/zedboard_axi_dma.srcs/sources_1/bd/zedboard_axi_dma/ip/zedboard_axi_dma_auto_us_2/zedboard_axi_dma_auto_us_2_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'zedboard_axi_dma_auto_us_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/git_repos/mnist_neuralnet/fpga/5_18_dmagithub/Vivado/zedboard_axi_dma/zedboard_axi_dma.srcs/sources_1/bd/zedboard_axi_dma/ip/zedboard_axi_dma_auto_us_2/zedboard_axi_dma_auto_us_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zedboard_axi_dma_auto_us_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
