# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/git_repos/mnist_neuralnet/fpga/milestone2/projects/DP_bram/DP_bram.srcs/sources_1/bd/axi_bram_block/ip/axi_bram_block_auto_pc_0/axi_bram_block_auto_pc_0.xci
# IP: The module: 'axi_bram_block_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/DP_bram/DP_bram.srcs/sources_1/bd/axi_bram_block/ip/axi_bram_block_auto_pc_0/axi_bram_block_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_bram_block_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/git_repos/mnist_neuralnet/fpga/milestone2/projects/DP_bram/DP_bram.srcs/sources_1/bd/axi_bram_block/ip/axi_bram_block_auto_pc_0/axi_bram_block_auto_pc_0.xci
# IP: The module: 'axi_bram_block_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/git_repos/mnist_neuralnet/fpga/milestone2/projects/DP_bram/DP_bram.srcs/sources_1/bd/axi_bram_block/ip/axi_bram_block_auto_pc_0/axi_bram_block_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_bram_block_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
